import type { Config } from "tailwindcss"

const config = {
  darkMode: ["class"],
  content: [
    "./src/**/*.{astro,ts,tsx,md,mdx}",
    "./public/**/*.html",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        outline: "#849495",
        "surface-tint": "#FD4E27",
        "surface-container-low": "#1c1b1b",
        "on-surface-variant": "#b9caca",
        "inverse-surface": "#e5e2e1",
        "surface-bright": "#3a3939",
        "surface-container-highest": "#353534",
        "primary-fixed-dim": "#FD4E27",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-fixed-variant": "#474746",
        "secondary-fixed": "#e5e2e1",
        "on-tertiary": "#313030",
        "on-surface": "#e5e2e1",
        background: "#050505",
        secondary: "#c8c6c5",
        "inverse-on-surface": "#313030",
        tertiary: "#fdf9f9",
        "outline-variant": "#3a494a",
        "inverse-primary": "#9A3412",
        "surface-variant": "#353534",
        "tertiary-fixed-dim": "#c8c6c5",
        "tertiary-fixed": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "on-primary": "#2A1000",
        "on-background": "#e5e2e1",
        "surface-container": "#201f1f",
        "on-error": "#690005",
        "primary-fixed": "#FFA88F",
        "surface-dim": "#131313",
        "on-secondary-fixed": "#1c1b1b",
        "primary-container": "#FD4E27",
        surface: "#131313",
        "on-secondary-container": "#bab8b7",
        "on-secondary-fixed-variant": "#474646",
        "on-tertiary-fixed": "#1c1b1b",
        "secondary-container": "#4a4949",
        "on-secondary": "#313030",
        "on-primary-fixed": "#2A1000",
        "on-primary-fixed-variant": "#7C2D12",
        "on-primary-container": "#431407",
        "surface-container-high": "#2a2a2a",
        primary: "#e9feff",
        "on-tertiary-container": "#626161",
        "secondary-fixed-dim": "#c8c6c5",
        "tertiary-container": "#e0dddc",
        error: "#ffb4ab",
        "error-container": "#93000a",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        foreground: "hsl(var(--foreground))",
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        display: ["Syne", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-xl": ["84px", { lineHeight: "92px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "display-xl-mobile": ["48px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
      },
      spacing: {
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "stack-lg": "32px",
        "section-gap": "120px",
        gutter: "24px",
        "stack-md": "16px",
        "container-max": "1280px",
        "stack-sm": "8px",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-20px)" },
        },
        "fade-up": {
          from: { opacity: "0", transform: "translateY(24px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        float: "float 6s ease-in-out infinite",
        "fade-up": "fade-up 0.5s cubic-bezier(0.4, 0, 0.2, 1) both",
        "fade-in": "fade-in 0.5s cubic-bezier(0.4, 0, 0.2, 1) both",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config

export default config
